// This file is generated by `pnpm generate:db-contracts` from the native contract
// types in src-tauri/src/database/{error,types}.rs. Do not edit by hand.

export type ErrorCode = "database_busy" | "database_locked" | "database_not_ready" | "database_update_required" | "unauthorized_caller" | "schema_too_old" | "schema_too_new" | "database_invalid" | "database_corrupt" | "backup_unavailable" | "restore_failed" | "operation_id_conflict" | "amount_out_of_range" | "invalid_ulid" | "invalid_date" | "invalid_input" | "recovery_required";
export type MetaKey = "stage" | "schema_version" | "retryable";
export type DbError = { code: ErrorCode, meta: { [key in string]: string }, };
export type LifecycleState = "uninitialized" | "initializing" | "ready" | "recovery_required" | "restoring";
export type StartupStage = "checking" | "backing_up" | "migrating" | "verifying";
export type RecoveryContext = { 
/**
 * Stable error code that triggered recovery.
 */
code: ErrorCode, 
/**
 * Whether the failure is retryable without a restore.
 */
retryable: boolean, };
export type OperationId = string;
export type IsoDate = string;
export type Page<T> = { items: Array<T>, total: number, offset: number, limit: number, };
export type Patch<T> = { "kind": "omitted" } | { "kind": "explicit_null" } | { "kind": "replace", value: T, };
export type AccountType = "checking" | "savings" | "cash" | "credit_card" | "loan_to_person" | "loan_from_person";
export type Account = { id: string, name: string, type: AccountType, counterparty: string | null, currency: string, archived: number, created_at: string, updated_at: string, };
export type AccountWithBalance = { id: string, name: string, type: AccountType, counterparty: string | null, currency: string, archived: number, created_at: string, updated_at: string, balance: number, };
export type NewAccount = { name: string, type: AccountType, counterparty: string | null, currency: string, initial_balance: number | null, initial_balance_date: string | null, };
export type AccountPatch = { name: string | null, type: AccountType | null, counterparty: Patch<string>, archived: number | null, };
export type TransactionKind = "expense" | "income" | "transfer" | "refund" | "adjustment";
export type Transaction = { id: string, kind: TransactionKind, date: string, amount: number, account_id: string, transfer_account_id: string | null, transfer_pair_id: string | null, refund_of_id: string | null, tag_id: string | null, payee: string | null, description: string | null, created_at: string, updated_at: string, };
export type NewTransaction = { kind: TransactionKind, date: string, amount: number, account_id: string, transfer_account_id: string | null, refund_of_id: string | null, tag_id: string | null, payee: string | null, description: string | null, };
export type TransactionFilter = { account_id: string | null, kind: TransactionKind | null, tag_id: string | null, payee: string | null, date_from: string | null, date_to: string | null, query: string | null, limit: number | null, offset: number | null, };
export type TransactionPatch = { date: string | null, amount: number | null, transfer_account_id: string | null, tag_id: Patch<string>, payee: Patch<string>, description: Patch<string>, };
export type Bucket = { id: string, name: string, is_system: number, budgetable: number, rollover_enabled: number, sort_order: number, created_at: string, updated_at: string, };
export type Tag = { id: string, type_id: string, name: string, is_system: number, sort_order: number, created_at: string, updated_at: string, };
export type TagDeleteInfo = { affected_count: number, affected_total: number, };
export type Budget = { id: string, type_id: string, month: string, allocated: number, created_at: string, updated_at: string, };
export type BudgetSummary = { type_id: string, month: string, allocated: number, spent: number, remaining: number, rolled_over: number, available: number, };
