// This file is generated by `pnpm generate:db-contracts` from the native contract
// types in src-tauri/src/database/{error,types}.rs. Do not edit by hand.

export type ErrorCode = "database_busy" | "database_locked" | "database_not_ready" | "database_update_required" | "unauthorized_caller" | "schema_too_old" | "schema_too_new" | "database_invalid" | "database_corrupt" | "backup_unavailable" | "restore_failed" | "operation_id_conflict" | "amount_out_of_range" | "invalid_ulid" | "invalid_date" | "invalid_input" | "recovery_required";
export type MetaKey = "stage" | "schema_version" | "retryable";
export type DbError = { code: ErrorCode, meta: { [key in string]: string }, };
export type LifecycleState = "uninitialized" | "initializing" | "ready" | "recovery_required" | "restoring";
export type StartupStage = "checking" | "backing_up" | "migrating" | "verifying";
export type RecoveryContext = { 
/**
 * Stable error code that triggered recovery.
 */
code: ErrorCode, 
/**
 * Whether the failure is retryable without a restore.
 */
retryable: boolean, };
export type OperationId = string;
export type IsoDate = string;
export type Page<T> = { items: Array<T>, total: number, offset: number, limit: number, };
export type Patch<T> = { "kind": "omitted" } | { "kind": "explicit_null" } | { "kind": "replace", value: T, };
