//! Native database integrity boundary contracts.
//!
//! Task 1 scope: the stable error envelope, common DTO types, and the
//! TypeScript binding generator. The executor thread, connection policy, OS
//! lock, and migration registry arrive in later tasks.

pub mod error;
pub mod types;

pub use error::{validate_money, DbError, DbResult, ErrorCode, MetaKey};
pub use types::{
    validate_bounded_list, validate_bounded_text, IsoDate, LifecycleState, OperationId, Page,
    Patch, RecoveryContext, StartupStage,
};

/// Header written above the generated bindings.
const GENERATED_HEADER: &str = "\
// This file is generated by `pnpm generate:db-contracts` from the native contract
// types in src-tauri/src/database/{error,types}.rs. Do not edit by hand.
";

/// Generate the complete TypeScript bindings for the native database contracts.
///
/// Large integers map to `number` because every monetary and version value is
/// bounded to JavaScript's safe integer range at the IPC boundary. The output
/// is built deterministically so a `--check` pass compares bytes exactly.
pub fn generate_bindings() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    push_decl(&mut out, "ErrorCode", &format!(
        "{};",
        error_code_union()
    ));
    push_decl(&mut out, "MetaKey", &format!(
        "{};",
        meta_key_union()
    ));
    push_decl(&mut out, "DbError", "{ code: ErrorCode, meta: { [key in string]: string }, };");
    push_decl(&mut out, "LifecycleState", &format!(
        "{};",
        lifecycle_union()
    ));
    push_decl(&mut out, "StartupStage", &format!(
        "{};",
        startup_stage_union()
    ));
    push_decl(
        &mut out,
        "RecoveryContext",
        "{ code: ErrorCode, retryable: boolean, };",
    );
    push_decl(&mut out, "OperationId", "string;");
    push_decl(&mut out, "IsoDate", "string;");
    push_decl(
        &mut out,
        "Page<T>",
        "{ items: Array<T>, total: number, offset: number, limit: number, };",
    );
    push_decl(
        &mut out,
        "Patch<T>",
        "{ kind: \"omitted\" } | { kind: \"explicit_null\" } | { kind: \"replace\", value: T };",
    );

    out
}

fn push_decl(out: &mut String, name: &str, body: &str) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    out.push_str(body);
    out.push('\n');
}

/// Union of stable snake_case error code literals.
fn error_code_union() -> String {
    let variants: &[&str] = &[
        "database_busy",
        "database_locked",
        "database_not_ready",
        "database_update_required",
        "unauthorized_caller",
        "schema_too_old",
        "schema_too_new",
        "database_invalid",
        "database_corrupt",
        "backup_unavailable",
        "restore_failed",
        "operation_id_conflict",
        "amount_out_of_range",
        "invalid_ulid",
        "invalid_date",
        "invalid_input",
        "recovery_required",
    ];
    variants
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Union of allowlisted error-metadata keys.
fn meta_key_union() -> String {
    let variants: &[&str] = &["stage", "schema_version", "retryable"];
    variants
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Union of lifecycle states.
fn lifecycle_union() -> String {
    let variants: &[&str] =
        &["uninitialized", "initializing", "ready", "recovery_required", "restoring"];
    variants
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

/// Union of startup sub-stages.
fn startup_stage_union() -> String {
    let variants: &[&str] = &["checking", "backing_up", "migrating", "verifying"];
    variants
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}
