//! Native database integrity boundary contracts.
//!
//! Task 1 scope: the stable error envelope, common DTO types, and the
//! TypeScript binding generator. Task 2 scope: the dedicated executor thread,
//! lifecycle snapshot, exact connection policy, and authoritative OS lock.

pub mod backup;
pub mod connection;
pub mod error;
pub mod executor;
pub mod lock;
pub mod manifest;
pub mod migrations;
pub mod types;

pub use backup::{
    cleanup_interrupted_publications, discover_verified_backups, publish_backup,
    retention_deletions, BackupFailurePoint,
};
pub use connection::{open_live, open_read_only, DatabasePaths};
pub use error::{validate_money, DbError, DbResult, ErrorCode, MetaKey};
pub use executor::{DatabaseManager, ExecutorState};
pub use lock::ProcessLock;
pub use manifest::{inspect_schema, validate_manifest, InvalidSchemaReason, SchemaInspection};
pub use migrations::{
    bootstrap_current, migrate_supported, run_migrations, FailurePoint, Migration, MIGRATIONS,
    LATEST_SCHEMA_VERSION, MIN_SUPPORTED_SCHEMA_VERSION,
};
pub use types::{
    validate_bounded_list, validate_bounded_text, BackupSummary, BackupToken, IsoDate,
    LifecycleState, OperationId, Page, Patch, RecoveryContext, StartupStage,
};

use ts_rs::{Config, TS};

/// Header written above the generated bindings.
const GENERATED_HEADER: &str = "\
// This file is generated by `pnpm generate:db-contracts` from the native contract
// types in src-tauri/src/database/{error,types}.rs. Do not edit by hand.
";

/// Generate the complete TypeScript bindings for the native database contracts.
///
/// Every declaration is derived from the Rust types through `ts-rs`, so adding
/// or renaming an enum variant or a DTO field changes the generated bytes and
/// fails `pnpm check:db-contracts` until the bindings are regenerated. There
/// is no hand-maintained list of names to drift from the source of truth.
///
/// Large integers map to `number` because every monetary and version value is
/// bounded to JavaScript's safe integer range at the IPC boundary. The output
/// is built deterministically so a `--check` pass compares bytes exactly.
pub fn generate_bindings() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    let cfg = Config::default().with_large_int("number");

    push_decl(&mut out, ErrorCode::decl(&cfg));
    push_decl(&mut out, MetaKey::decl(&cfg));
    push_decl(&mut out, DbError::decl(&cfg));
    push_decl(&mut out, LifecycleState::decl(&cfg));
    push_decl(&mut out, StartupStage::decl(&cfg));
    push_decl(&mut out, RecoveryContext::decl(&cfg));
    push_decl(&mut out, OperationId::decl(&cfg));
    push_decl(&mut out, IsoDate::decl(&cfg));
    // ts-rs substitutes generic parameters with placeholders in `decl()`, so
    // `Page::<i64>::decl()` yields the generic `type Page<T> = ...`.
    push_decl(&mut out, Page::<i64>::decl(&cfg));
    push_decl(&mut out, Patch::<i64>::decl(&cfg));

    out
}

/// Append one `ts-rs` declaration as an exported type alias.
///
/// `ts-rs` emits `type NAME = ...;` without the `export` keyword and may
/// include JSDoc comments and internal newlines; prefix the `export` and
/// normalize the trailing whitespace so the output is stable across runs.
fn push_decl(out: &mut String, decl: String) {
    out.push_str("export ");
    out.push_str(decl.trim());
    out.push('\n');
}
